# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowsSinDatos.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.LbQuestion = QtWidgets.QLabel(Dialog)
        self.LbQuestion.setGeometry(QtCore.QRect(100, 140, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.LbQuestion.setFont(font)
        self.LbQuestion.setScaledContents(False)
        self.LbQuestion.setObjectName("LbQuestion")
        self.LbQuestion_2 = QtWidgets.QLabel(Dialog)
        self.LbQuestion_2.setGeometry(QtCore.QRect(140, 180, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.LbQuestion_2.setFont(font)
        self.LbQuestion_2.setScaledContents(False)
        self.LbQuestion_2.setObjectName("LbQuestion_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 30, 131, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("information.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Information"))
        self.LbQuestion.setText(_translate("Dialog", " El dni ingresado "))
        self.LbQuestion_2.setText(_translate("Dialog", "no existe."))
