# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowsAviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aviso(object):
    def setupUi(self, Aviso):
        Aviso.setObjectName("Aviso")
        Aviso.resize(392, 277)
        self.BtnBoxAvisoYes = QtWidgets.QPushButton(Aviso)
        self.BtnBoxAvisoYes.setGeometry(QtCore.QRect(100, 180, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.BtnBoxAvisoYes.setFont(font)
        self.BtnBoxAvisoYes.setAcceptDrops(False)
        self.BtnBoxAvisoYes.setObjectName("BtnBoxAvisoYes")
        self.BtnBoxAvisoNo = QtWidgets.QPushButton(Aviso)
        self.BtnBoxAvisoNo.setGeometry(QtCore.QRect(210, 180, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.BtnBoxAvisoNo.setFont(font)
        self.BtnBoxAvisoNo.setObjectName("BtnBoxAvisoNo")
        self.label = QtWidgets.QLabel(Aviso)
        self.label.setGeometry(QtCore.QRect(150, 30, 81, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("warning.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.LbQuestion = QtWidgets.QLabel(Aviso)
        self.LbQuestion.setGeometry(QtCore.QRect(110, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        self.LbQuestion.setFont(font)
        self.LbQuestion.setScaledContents(False)
        self.LbQuestion.setObjectName("LbQuestion")

        self.retranslateUi(Aviso)
        QtCore.QMetaObject.connectSlotsByName(Aviso)

    def retranslateUi(self, Aviso):
        _translate = QtCore.QCoreApplication.translate
        Aviso.setWindowTitle(_translate("Aviso", "Aviso"))
        self.BtnBoxAvisoYes.setText(_translate("Aviso", "Yes"))
        self.BtnBoxAvisoNo.setText(_translate("Aviso", "No"))
        self.LbQuestion.setText(_translate("Aviso", "¿Desea Salir?"))
